spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/plus?useSSL=true&serverTimezone=UTC
    username: root
    password: '!@#mhl123123'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
server:
  port: 8081
application:
  cors:
    allowed-origins: http://localhost:4200,http://localhost:4201
  web:
    upload-path: D:\static
